package fr.vajin.snakerpg.database.exceptions;

public class LaPartieNexistePasOhZutCestVraimentTropNulMaisDuCoupOnEstObligesDeRenvoyerUneExceptionOuAlorsPeutEtreDeRenvoyerNullMaisJePrefereLesExceptions extends Exception {
}
